user_events:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}"
      host: rdbms
      pass:  "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: dev
